flight(istanbul,rize).
flight(rize,istanbul).
flight(istanbul,van).
flight(van,istanbul).
flight(istanbul,ankara).
flight(ankara,istanbul).
flight(istanbul,gaziantep).
flight(gaziantep,istanbul).
flight(istanbul,antalya).
flight(antalya,istanbul).
flight(istanbul,izmir).
flight(izmir,istanbul).
flight(izmir,isparta).
flight(isparta,izmir).
flight(isparta,burdur).
flight(burdur,isparta).
flight(rize,van).
flight(van,rize).
flight(van,ankara).
flight(ankara,van).
flight(ankara,konya).
flight(konya,ankara).
flight(konya,antalya).
flight(antalya,konya).
flight(antalya,gaziantep).
flight(gaziantep,antalya).
flight(erzincan,edremit).
flight(edremit,erzincan).
flight(edremit,edirne).
flight(edirne,edremit).

distance(istanbul,rize,970).
distance(rize,istanbul,970).
distance(istanbul,van,1264).
distance(van,istanbul,1264).
distance(istanbul,ankara,352).
distance(ankara,istanbul,352).
distance(istanbul,gaziantep,850).
distance(gaziantep,istanbul,850).
distance(istanbul,antalya,481).
distance(antalya,istanbul,481).
distance(istanbul,izmir,328).
distance(izmir,istanbul,328).
distance(izmir,isparta,307).
distance(isparta,izmir,307).
distance(isparta,burdur,24).
distance(burdur,isparta,24).
distance(rize,van,373).
distance(van,rize,373).
distance(van,ankara,920).
distance(ankara,van,920).
distance(ankara,konya,230).
distance(konya,ankara,230).
distance(konya,antalya,191).
distance(antalya,konya,191).
distance(antalya,gaziantep,594).
distance(gaziantep,antalya,594).
distance(erzincan,edremit,1026).
distance(edremit,erzincan,1026).
distance(edremit,edirne,245).
distance(edirne,edremit,245).


sroute(X,Y,C):-
min(X,Y,C,[X]).

min(A,B,C,PATH):-
flight(A,B),
distance(A,B,C),
reverse([B|PATH],RESULT)->
write(RESULT).

min(A,B,C,PATH):-
flight(A,D),
distance(A,D,COST),
\+member(D,PATH),
D \== B,
min(D,B,C2,[D|PATH]),
C is COST + C2.
